apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  labels:
    io.kompose.service: grafana
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
      nodePort: 32000
  selector:
    io.kompose.service: grafana
  type: LoadBalancer
