apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data
  labels:
   io.kompose.service: prometheus-data
   name: prometheus-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi