kind: PersistentVolume
apiVersion: v1
metadata:
  name: prometheus-data
  labels:
    name: prometheus-data
spec:
  capacity:
    storage: 1Gi
  storageClassName: standard
  accessModes:
    - ReadWriteMany